USE ANS;

#Posts table

ALTER TABLE Posts ADD CONSTRAINT PK_ID PRIMARY KEY (Id);

ALTER TABLE Posts MODIFY Id INT NOT NULL AUTO_INCREMENT;

#Comments Table
ALTER TABLE Comments ADD CONSTRAINT PK_ID PRIMARY KEY (Id);

ALTER TABLE Comments MODIFY Id INT NOT NULL AUTO_INCREMENT;
DELETE FROM Comments WHERE PostId NOT IN (SELECT Id FROM Posts);
#Foriegn Key between posts and comments
ALTER TABLE Comments ADD CONSTRAINT FK_POSTID_Comments FOREIGN KEY (PostId)
REFERENCES Posts (Id) ON UPDATE CASCADE ON DELETE CASCADE;

#Topics table
ALTER TABLE Topics ADD CONSTRAINT PK_ID PRIMARY KEY (Id);
ALTER TABLE Topics MODIFY Id  INT NOT NULL AUTO_INCREMENT;

#TopicKeywordMap table
ALTER TABLE TopicKeywordMap ADD CONSTRAINT PK_ID PRIMARY KEY (Id);
ALTER TABLE TopicKeywordMap MODIFY Id  INT NOT NULL AUTO_INCREMENT;

ALTER TABLE TopicKeywordMap ADD CONSTRAINT FK_TOPICID FOREIGN KEY (TopicId)
REFERENCES Topics (Id) ON UPDATE CASCADE ON DELETE CASCADE;

#PostTopicMap table
ALTER TABLE PostTopicMap ADD CONSTRAINT PK_ID PRIMARY KEY (Id);
ALTER TABLE PostTopicMap MODIFY Id  INT NOT NULL AUTO_INCREMENT;

ALTER TABLE PostTopicMap ADD CONSTRAINT FK_TOPICID_PostTopicMap FOREIGN KEY (TopicId)
REFERENCES Topics (Id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE PostTopicMap ADD CONSTRAINT FK_POSTID_PostTopicMap FOREIGN KEY (PostId)
REFERENCES Posts (Id) ON UPDATE CASCADE ON DELETE CASCADE;



#SELECT DISTINCT PostId FROM Comments;

#SELECT * FROM Posts WHERE Id IN (
#SELECT PostId FROM Comments WHERE PostId NOT IN (SELECT Id FROM Posts));

#SELECT PostId FROM Comments WHERE PostId NOT IN (SELECT Id FROM Posts);
#SELECT COUNT(*) FROM Comments;
#SELECT COUNT(*) FROM Comments WHERE PostId IN 
#(SELECT PostId FROM Comments WHERE PostId NOT IN (SELECT Id FROM Posts));
#DELETE FROM Comments WHERE PostId NOT IN (SELECT Id FROM Posts);

